plugins: 
    - jest

env: 
    es2021: true

extends: 
    - 'airbnb-base'
    - 'plugin:jest/recommended'

parserOptions: 
    ecmaVersion: 12
    sourceType: module

rules: {
    no-console: off,
    import/extensions: off,
    no-await-in-loop: off,
    no-inline-comments: off,
    no-underscore-dangle: [2, { allow: [__filename, __dirname] }]
}


